window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t199_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuList=rec.querySelectorAll('.t199__js__menu');var togglerList=rec.querySelectorAll('.t199__js__menu-toggler');var burger=rec.querySelector('.t-menuburger');var burgerOpenClass='t-menuburger-opened';Array.prototype.forEach.call(menuList,function(menu){var menuItemList=menu.querySelectorAll('.t199__menu-item');Array.prototype.forEach.call(menuItemList,function(menuItem){var href=menuItem.getAttribute('href');if(href&&href.indexOf('#')!==-1&&href.substring(0,9)!=='#submenu:'){menuItem.addEventListener('click',function(){document.body.classList.remove('t199__is__menu')})}});var menuLinkList=menu.querySelectorAll('.t199__menu-item-wrap .t-menusub__link-item');Array.prototype.forEach.call(menuLinkList,function(menuLink){menuLink.addEventListener('click',function(){document.body.classList.remove('t199__is__menu')})})});Array.prototype.forEach.call(togglerList,function(toggler){toggler.addEventListener('click',function(e){e.stopPropagation();e.preventDefault();document.body.classList.toggle('t199__is__menu');burger.classList.contains(burgerOpenClass)?burger.classList.remove(burgerOpenClass):burger.classList.add(burgerOpenClass)})});document.addEventListener('click',function(e){if(!e.target.closest('.t199__js__menu')&&!e.target.closest('.t-menusub__menu--fullscreen__nav-arrow')){document.body.classList.remove('t199__is__menu')}});var allMenu=document.querySelectorAll('.t199__mmenu');Array.prototype.forEach.call(allMenu,function(menu){menu.addEventListener('clickedAnchorInTooltipMenu',function(){document.body.classList.remove('t199__is__menu')})})}
function t199_positionHeader(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var header=rec.querySelector('.t199__js__header');var bgColor=header?header.style.backgroundColor||window.getComputedStyle(header).backgroundColor:'';t199_positionHeaderOnScroll(header,bgColor);window.addEventListener('scroll',function(){t199_positionHeaderOnScroll(header,bgColor)})}
function t199_positionHeaderOnScroll(header,bgColor){if(window.pageYOffset<=0){if(header)header.classList.remove('t199__is__active');if(header)header.style.backgroundColor=bgColor}else if(header&&!header.classList.contains('t199__is__active')){header.classList.add('t199__is__active');header.style.backgroundColor=''}}
function t480_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t480');if(!container)return;var isJquery=typeof jQuery!=='undefined';t480_setHeight(recId);if(window.isMobile){if(isJquery){$(window).on('orientationchange',t_throttle(function(){setTimeout(function(){t480_setHeight(recId)},200)}))}else{window.addEventListener('orientationchange',t_throttle(function(){setTimeout(function(){t480_setHeight(recId)},200)}))}}else{window.addEventListener('resize',t_throttle(function(){if(window.noAdaptive&&window.noAdaptive===!0&&window.isMobile)return;t480_setHeight(recId)}))}
if(isJquery){$(container).on('displayChanged',function(){t480_setHeight(recId)})}else{container.addEventListener('displayChanged',function(){t480_setHeight(recId)})}}
function t480_setHeight(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t480');if(!container)return;var sizer=rec.querySelector('.t480__sizer');var sizerStyle=getComputedStyle(sizer,null);var sizerPaddingTop=parseInt(sizerStyle.paddingTop);var sizerPaddingBottom=parseInt(sizerStyle.paddingBottom);var sizerPaddingLeft=parseInt(sizerStyle.paddingLeft);var sizerPaddingRight=parseInt(sizerStyle.paddingRight);var sizerHeight=sizer.clientHeight-(sizerPaddingTop+sizerPaddingBottom);var sizerWidth=sizer.clientWidth-(sizerPaddingLeft+sizerPaddingRight);var ratio=sizerWidth/sizerHeight;var imgWrapper=rec.querySelector('.t480__blockimg');var imgWidth=imgWrapper.clientWidth;var sizerAttrStyle=sizer.getAttribute('style');var windowHeight=window.innerHeight;if(window.isMobile&&sizerAttrStyle&&sizerAttrStyle.indexOf('vh')!==-1){sizerHeight=document.documentElement.clientHeight*parseFloat(windowHeight/sizerHeight);imgWrapper.style.height=imgWidth/ratio+'px'}else if(sizerHeight!=windowHeight){imgWrapper.style.height=imgWidth/ratio+'px'}}
function t939_init(recId){t_onFuncLoad('t_card__moveClickOnCard',function(){t_card__moveClickOnCard(recId)});t_onFuncLoad('t_card__addFocusOnTab',function(){t_card__addFocusOnTab(recId)})}
function t843_init(recId){var rec=document.querySelector('#rec'+recId);if(!rec)return;var container=rec.querySelector('.t843');if(!container)return;t_onFuncLoad('t_card__moveClickOnCard',function(){t_card__moveClickOnCard(recId)});t_onFuncLoad('t_card__addFocusOnTab',function(){t_card__addFocusOnTab(recId)});t843_setHeight(recId);window.addEventListener('resize',t_throttle(function(){if(window.noAdaptive&&window.noAdaptive===!0&&window.isMobile)return;t843_setHeight(recId)}));if(typeof jQuery!=='undefined'){$(container).bind('displayChanged',function(){t843_setHeight(recId)})}else{container.addEventListener('displayChanged',function(){t843_setHeight(recId)})}
if(container&&container.classList.contains('t843__previewmode')){setInterval(function(){t843_setHeight(recId)},5000)}}
function t843_setHeight(recId){var rec=document.querySelector('#rec'+recId);if(!rec)return;var container=rec.querySelector('.t843');if(!container)return;var blockImages=rec.querySelectorAll('.t843__blockimg');var isLoaded=!0;for(var i=0;i<blockImages.length;i++){var blockImage=blockImages[i];var width=blockImage.getAttribute('data-image-width');var height=blockImage.getAttribute('data-image-height');var ratio=height/width;var padding=ratio*100;blockImage.style.paddingBottom=padding+'%';if(!blockImage.classList.contains('loaded')){isLoaded=!1}}
if(window.innerWidth>960){var textWraps=rec.querySelectorAll('.t843__textwrapper');var deskImages=rec.querySelectorAll('.t843__desktopimg');for(var i=0;i<textWraps.length;i++){textWraps[i].style.height=deskImages[i].clientHeight+'px'}}
if(!isLoaded){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}}
function t389_scrollToTop(){var duration=700;var difference=window.pageYOffset;var step=(10*difference)/duration;var timer=setInterval(function(){difference-=step;window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if(window.pageYOffset===0){document.body.removeAttribute('data-scrollable');clearInterval(timer)}},10)}